# Generated by Django 4.1.5 on 2023-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('Title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
