# Generated by Django 4.1.5 on 2023-01-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='Company',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
