# Generated by Django 4.1.5 on 2023-01-29 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0003_tool_company_tool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='users',
            field=models.ManyToManyField(related_name='tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tools.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
