# Generated by Django 4.1.5 on 2023-01-31 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0006_authcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
